github:
  prebuilds:
    addCheck: false

tasks:
  - name: js
    init: |
      cd js
      npm install -g npm
      npm install
    command: |
      sudo apt install tig
      npm install -g npm eslint prettier
  - name: python
    command: |
      cd python
      pip install -U pip esbonio
      virtualenv .venv
      source .venv/bin/activate
      pip install -U pip setuptools tox esbonio
      pip install -e .
      tox
  - name: kotlin
    command: |
      cd kotlin
      curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.46.1/ktlint && chmod a+x ktlint
      ./gradlew build

gitConfig:
  alias.co: checkout
  alias.ci: commit
  alias.amend: "commit --amend --reset-author --no-edit"
  core.autocrlf: input
  core.whitespace: blank-at-eol,blank-at-eof,indent-with-tab
  pull.rebase: "false"

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - eg2.vscode-npm-script
    - graphql.vscode-graphql
    - ms-python.python
    - lextudio.restructuredtext
    - trond-snekvik.simple-rst
    - mathiasfrohlich.kotlin
