name: Kotlin

on: [pull_request]

jobs:
  kotlin_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: |
          cd kotlin
          ./gradlew build

  kotlin_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: |
          cd kotlin
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.46.1/ktlint && chmod a+x ktlint
          ./ktlint
